name: meta_
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - pip
  - numpy>=2,<3
  - scipy
  - pandas
  - matplotlib
  - tqdm
  - gym=0.26.2
  - h5py
  - openpyxl
  - cloudpickle
  - pytorch
  - tensorboard
  - pip:
      - tensorboard-logger
      - opencv-python
